name: todo_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.2


dependencies:
  flutter:
    sdk: flutter
  uuid: ^3.0.6

  firebase_core: ^2.24.2
  firebase_analytics: ^10.8.0
  cloud_firestore: ^4.14.0

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:



  uses-material-design: true
