// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD36kzrLLdgJ_KakHgE3Maoqx-9X5R-ko8',
    appId: '1:820708750599:web:3e0f3fe8b2e3b683b101a2',
    messagingSenderId: '820708750599',
    projectId: 'flutter-todo-app-f4f48',
    authDomain: 'flutter-todo-app-f4f48.firebaseapp.com',
    storageBucket: 'flutter-todo-app-f4f48.appspot.com',
  );
}
